import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import MiddleSection from "../components/MiddleSection";
import Navigation from "../components/Navigation";
import RightSection from "../components/RightSection";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className=" bg-slate-400 h-screen  ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:grid lg:grid-cols-[1fr,min-content,1fr] lg:h-full px-7 py-5  ">
        <Navigation />
        <MiddleSection />
        <RightSection />
      </main>
    </div>
  );
};

export default Home;
