import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Dashboard from "../components/Dashboard";
import AroundYou from "../components/middle-section/AroundYou";
import MiddleHeader from "../components/middle-section/Header";
import Header from "../components/middle-section/Header";
import HikingCards from "../components/middle-section/HikingCards";
import LongCard from "../components/middle-section/LongCard";
import MiddleSection from "../components/MiddleSection";
import Navigation from "../components/Navigation";
import CalendarCards from "../components/right-section/CalendarCards";
import CalendarHikes from "../components/right-section/CalendarHikes";
import UserProfileCard from "../components/right-section/UserProfileCard";
import RightSection from "../components/RightSection";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="  h-screen  ">
      <Head>
        <title>Hiking app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard>
        <Navigation />

        <MiddleSection>
          <div className=" grid  h-full gap-8">
            <MiddleHeader />
            <div className="grid grid-cols-3 gap-12  ">
              <HikingCards />
              <HikingCards />
              <HikingCards />
            </div>
            <div className="grid grid-cols-3 gap-12">
              <div className="col-span-2">
                <AroundYou />
              </div>
              {/* card-cta */}
              <div className="bg-red-500 rounded-2xl"></div>
            </div>
          </div>
        </MiddleSection>
        <RightSection />
      </Dashboard>
    </div>
  );
};

export default Home;
